obj-y      += axe_eth.o

axe_eth-objs := ivo_eth.o stmmac_main.o stmmac_ethtool.o stmmac_mdio.o stmmac_timer.o   \
              dwmac_lib.o dwmac1000_core.o  dwmac1000_dma.o     \
              dwmac100_core.o dwmac100_dma.o enh_desc.o  norm_desc.o
